Repository CruGlobal/ab_service_api_sails, pull requests merged in 2024-01, with the labels that each got.

#125 Jh/mobile pwa
  api/controllers/auth/whoami.js
  api/controllers/mobile/app.js
  api/controllers/mobile/favicon.js
  api/controllers/mobile/manifest.js
  api/controllers/mobile/qr.js
  api/controllers/mobile/version.js
  api/policies/authUser.js
  config/policies.js
  config/routes.js
  views/mobile_manifest.ejs
  views/mobile_pwa.ejs
Labels: minor

#127 Initialize api_sails communication links to other services on boot up
  api/hooks/healthcheck.js
  config/bootstrap.js
Labels: skip-release

#128 enable compression middleware in test env
  config/env/test.js
Labels: patch

#130 Get more response parameters
  api/controllers/file_processor/file-base64-upload.js
Labels: patch

#129 Jh/performance preloader
  api/controllers/SiteController.js
  api/controllers/definition_manager/definition-for-role.js
  api/lib/cacheManager.js
  api/policies/authTenant.js
  api/policies/authUser.js
  config/bootstrap.js
  config/routes.js
  views/web_preloader.ejs
Labels: skip-release

#132 Jh/performance
  api/controllers/SiteController.js
  api/controllers/definition_manager/definition-for-role.js
  api/hooks/healthcheck.js
  api/lib/cacheManager.js
  api/policies/authTenant.js
  api/policies/authUser.js
  config/bootstrap.js
  config/routes.js
  views/web_preloader.ejs
Labels: minor
