Repository CruGlobal/ab_service_api_sails, pull requests merged in 2024-03, with the labels that each got.

#141 Fix clearing "all" tenant caches
  api/lib/cacheManager.js
Labels: patch

#144 Add new Testing Tools
  api/hooks/testLog.js
  api/hooks/versionCheck.js
  config/bootstrap.js
Labels: enhancement, minor

#148 `/home` less Auth
  README.md
  api/controllers/SiteController.js
  api/controllers/auth/login-start.js
  api/controllers/auth/login.js
  api/controllers/auth/okta-callback.js
  api/controllers/auth/okta-error.js
  api/controllers/auth/whoami.js
  api/controllers/mobile/app.js
  api/controllers/mobile/favicon.js
  api/controllers/mobile/manifest.js
  api/controllers/mobile/qr.js
  api/controllers/mobile/version.js
  api/helpers/user/find-with-cache.js
  api/hooks/initPassport.js
  api/lib/authUserCAS.js
  api/lib/authUserLocal.js
  api/lib/authUserOkta.js
  api/lib/authUserRelay.js
  api/lib/authUserToken.js
  api/policies/authTenant.js
  api/policies/authUser.js
  config/routes.js
  package-lock.json
  package.json
Labels: major

#150 Fix typo causing login errors not to be displayed
  api/controllers/auth/login.js
Labels: patch

#151 +Add log to see username when generate CSV file
  api/controllers/appbuilder/csv-export.js
Labels: patch
